### PR TITLE
Added burmese traditional units to definitions

### PR DESCRIPTION
**Pull request by eimg**
Added Burmese traditional units of Length, Mass, Volume and Time into existing definitions.

Ref 1: https://en.wikipedia.org/wiki/Myanmar_units_of_measurement
Ref 2: https://en.wikipedia.org/wiki/Burmese_calendar

### CODE REVIEW

**Comment by ben-ng** [comment]
woah, is there any way to fix the formatting so it's easier to review this?

**Comment by eimg** [comment]
Please see the last commit. I've fixed the code format issue.

**Comment by ben-ng** [comment]
It looks like you forgot to update the tests. Can you fix that?

**Comment by Taar** [comment]
Closing out old PRs

**Pull request closed without merging**
