### PR TITLE
Support binary and decimal digital conversions

### PR DESCRIPTION
**Pull request by bstoots**
* Remove digital definition.  Replace with digitalBin and digitalDec.
* digitalBin is defined according to IEC naming scheme where 1 kibibyte equals 1024 bytes and is abbreviated KiB.
* digitalDec is defined according to Metric naming scheme where 1 kilobyte equals 1000 bytes and is abbreviated KB.
* Updated test coverage for these newly split definitions.
* Updated TypeScript definitions.
* Updated README
* Removed errant GB to B conversion test from test/pressures.js

### CODE REVIEW

**Comment by gmicek** [comment]
+1 can we merge this ?

**Comment by bstoots** [comment]
> 
> 
> +1 can we merge this ?

FWIW I gave up waiting for this PR to be merged and forked the project.  The forked version is published on NPM here: https://www.npmjs.com/package/@bstoots/convert-units.

**Comment by gmicek** [comment]
Awesome, thanks! I think I'll use that

**Comment by Taar** [comment]
Closing out old PRs

**Pull request closed without merging**
