### PR TITLE
add the unit pieces

### PR DESCRIPTION
**Pull request by pgenta**
hope this will be useful

here I use the unit pieces used in https://www.justintools.com/unit-conversion/quantity.php?k1=units&k2=pieces but not all

### CODE REVIEW

**Comment by Taar** [comment]
Thanks for the PR! Would you be able to add some tests for these new units?

**Comment by pgenta** [comment]
I wish I could, but what kind of test would you like? sorry, for asking something basic like this, but I haven't been familiar with programming for too long and don't know much about testing

**Comment by Taar** [comment]
No worries! I recommend looking for resources to learn the basics of writing **unit tests**. The authors will be able to explain the basics better than I can. Specifically for this code base and the code you're submitting, we're mostly concerned with writing tests that verify the conversions from one unit to another are what we expect. For example, that converting `1 doz` to `pcs` results in the value of `12`. You'll also want to write a test for each possible conversion to make sure all possibilities are covered. Check out the `test` folder for some examples and a starting point. You'll be able to run the tests with the following command, `npm test`. Feel free to leave a comment here if you have any additional questions.

Also, would you be able to add the measure and units to the `README.md` file?

Thanks again!

**Comment by pgenta** [comment]
oh thanks for the information @Taar , yes i'll do the testing and add this measure and unit to the `readme.md` file,  but sorry it might take some time

**Comment by Taar** [comment]
Sorry to throw a wrench into the work you've completed so far. The project has moved to a different test runner called [Jest](https://jestjs.io/). This means you'll need to update your code to use the new test runner. Examples can be found [here](https://github.com/ben-ng/convert-units/blob/master/lib/definitions/__tests__/area.test.js). Also, test js files need to be placed in the `__tests__` directory in order to be noticed by Jest. Again, sorry! Let me know if you need help or have any questions.

**Comment by dmbarry86** [comment]
As well as writing a new test file for pieces (which should be placed in `lib/definitions/__tests__/pieces.test.js`) you would also need to update the existing test for [measures](https://github.com/ben-ng/convert-units/blob/master/lib/__tests__/measures.test.js) and [possibilities](https://github.com/ben-ng/convert-units/blob/master/lib/__tests__/possibilities.test.js) now you have added a new measure and new unit possiblities. If you run the command `npm run test` you will see the measure and possibilities tests that fail and need updating accordingly. I'm happy to help if you need any support.

**Comment by pgenta** [comment]
Thank you for all the feedback and information you provide, I will retest my code using a jest, and it is not a problem for me and thank you too for teaching me about this

**Comment by pgenta** [comment]
Screenshot (94)

hi guys, sorry it took too much time for this, but I have done my testing using jest and it has gone well so far, is this test correct enough ?, if not I can do it again happily.

if this test is enough then I will change the status of this PR to 'Ready for review'

that I've done here

1. Add the unit pieces
2. change `readme.md` file
3. add test file  in `lib\definitions\__tests__\pieces.test.js`

**Comment by dmbarry86** [comment]
Your screenshot just shows you running tests for pieces.  Did you also run all tests using `npm run jest` to check that everything else still passes? Remember you would need to update the measure and possibilities tests I mentioned. If you push your changes I am happy to take a look and advise of any changes.

**Comment by dmbarry86** [comment]
Also if you pull in latest master then I think that all checks will automatically run as an action in this pull request.

**Comment by pgenta** [comment]
> Your screenshot just shows you running tests for pieces. Did you also run all tests using `npm run jest` to check that everything else still passes? Remember you would need to update the measure and possibilities tests I mentioned. If you push your changes I am happy to take a look and advise of any changes.

oh sorry @dmbarry86  i forgot it, i will fix it this time, but is it okay if I change some of the test code if they don't pass ?

**Comment by pgenta** [comment]
Screenshot (95)

I have finished whether this is good enough ? i'm sorry for forgetting this

**Comment by dmbarry86** [comment]
Test updates look good to me. Thanks for making those changes @pgenta. I'll leave @Taar to finish the review now.

**Comment by pgenta** [comment]
oh thank you everyone, I am very happy with this, thank you for the guidance you have provided

**Pull request merged**
