### PR TITLE
feat: iec digital conversion

### LINKED ISSUE #261: (Re)Add support for IEC standard (bibit/bibyte)
Pull request https://github.com/convert-units/convert-units/pull/259 removed support for IEC standard (1KiB = 1024B) and replaced it with base 10 conversion (1KB = 1000B).

(Re)Add support for IEC standard while keeping the base 10 conversion:
```ts
export type DigitalUnits =
  | DigitalBitsUnits
  | DigitalBiBitsUnits
  | DigitalBytesUnits
  | DigitalBytesUnits;
export type DigitalSystems = 'bits' | 'bibits' | 'bytes' | 'bibytes';

export type DigitalBitsUnits = 'b' | 'Kb' | 'Mb' | 'Gb' | 'Tb';
export type DigitalBiBitsUnits = 'b' | 'Kib' | 'Mib' | 'Gib' | 'Tib';
export type DigitalBytesUnits = 'B' | 'KB' | 'MB' | 'GB' | 'TB';
export type DigitalBiBytesUnits = 'B' | 'KiB' | 'MiB' | 'GiB' | 'TiB';
```

### PR DESCRIPTION
**Pull request by carlocorradini**
Fix #261 
Added support for IEC digital units.

__Bibit__:
- `Kib`
- `Mib`
- `Gib`
- `Tib`

__Bibyte__:
- `KiB`
- `MiB`
- `GiB`
- `TiB`

Note that conversions are possible between all four units (*Bit*, *Bibit*, *Byte*, and *Bibyte*). 
It should be fully comparable to what Google's digital unit converter works/supports.

### CODE REVIEW

**Comment by carlocorradini** [comment]
@Taar Any update on this? 😥

**Review by Taar — COMMENTED** [review]
Thanks for taking the time to submit a PR! Unfortunately, I cannot accept the PR in its current state because there is a hidden bug in the changes. 

The issue comes from the fact that both `DigitalBitsUnits` and `DigitalBibitsUnits` share the same unit symbol, `b`. When either the [`.to`](https://github.com/convert-units/convert-units/blob/v3.0.0-beta.5/src/convert.ts#L95) or [`.from`](https://github.com/convert-units/convert-units/blob/v3.0.0-beta.5/src/convert.ts#L79) methods are called, the [`toUnit` ](https://github.com/convert-units/convert-units/blob/v3.0.0-beta.5/src/convert.ts#L256) method is used to figure out the unit, system, and measure that the passed string belongs to. Since the only information it receives is that string, there is no way for it to know if the user wanted `b` unit from the `bibits` system or the `b` unit from the `bits` system. The `toUnit` method will return the first occurrence of `b` it finds which means it's possible to get unexpected results.

With all that said, I think the better solution is to use longer names for the `bibits` `Bit` unit and the `bibytes` `Byte` unit. I'm leaning in that direction because I would like to avoid changing the unit names for the older units if possible. However, I'm open to discussing that further if others feels different.

Please let me know what you think! I can accept the PR once the bug is fixed. Which means that the changes to the `possibilities` method can also be removed.

**Comment by carlocorradini** [comment]
Agree. 
Any possible workaround without creating *bit* aliases? 
Can you add an example of a possible error? Since a bi/bibit has the same ratio, this should work, but currently I don't see it :/

Nevertheless, I think this library needs support for IEC digital units.

**Comment by Taar** [comment]
You're correct, `convert(10).from('GB').to('b')` would result in the same value but wouldn't you agree that there is no way to know which `b` unit is actually being used here? I think the issue becomes more clear when using other methods like [`toBest`](https://github.com/convert-units/convert-units/blob/v3.0.0-beta.5/src/convert.ts#L190) because it [doesn't just return a numerical value](https://github.com/convert-units/convert-units/blob/v3.0.0-beta.5/src/convert.ts#L241). 

I threw together [this example](https://codesandbox.io/s/bold-kilby-6uco0l?file=/src/index.ts) which shows that no matter how many times you run the code, it will always use the `bits` if the digital measure is used. But if you remove the `bits` system, it'll use the `bibits` system. This is because the code base assumes that there is only one unit with the name `b`.

Output from the example
```typescript
// with both bits and bibits systems
{val: 1.024, unit: "Kb", singular: "Kilobit", plural: "Kilobits"}
{abbr: "b", measure: "digital", system: "bits", singular: "Bit", plural: "Bits"}

// with only bibits system
{val: 1, unit: "Kib", singular: "Kibibit", plural: "Kibibits"}
{abbr: "b", measure: "digitalWithoutBits", system: "bibits", singular: "Bit", plural: "Bits"}
```

> Any possible workaround without creating bit aliases? 

It's not possible to support two different systems using the same unit name. The duplicate unit names will need to be changed so that they are unique.

**Comment by carlocorradini** [comment]
@Taar I see...

So, alias only? 😥

**Comment by carlocorradini** [comment]
@Taar Do you want to update the files?

**Pull request closed without merging**
