### PR TITLE
Add alternate names

### PR DESCRIPTION
**Pull request by matmar10**

### CODE REVIEW

**Comment by matmar10** [comment]
NOTE: depends on PR #99

**Comment by Taar** [comment]
Closing out old PRs

**Comment by matmar10** [comment]
Why was this closed? Can this PR be considered please? AFAIK there were no breaking changes, and it included proper unit test coverage.

**Comment by matmar10** [comment]
Ah, understood the whole project has been reworked into TS with a new structure and this is no longer a seamless merge.

**Comment by dmbarry86** [comment]
Test suite has also been migrated to Jest.

**Pull request closed without merging**
